services:
  interval:
    image: alexarena/interval-server:1.0.3
    profiles:
      - interval-server
    env_file: .env
    restart: always
    ports:
      - 3000:3000
      - 3033:3033
    depends_on:
      postgres:
        condition: service_healthy
 
  postgres:
    image: postgres:17.0
    profiles:
      - db
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
 
  adminer:
    image: adminer:4.8.1
    profiles:
      - db
    env_file: .env
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
